# Generated by Django 4.2 on 2023-04-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0004_remove_blog_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
