# Generated by Django 4.2 on 2023-04-12 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_rename_blog_productcomment_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogCategory',
            new_name='BlogC',
        ),
        migrations.RenameModel(
            old_name='ProductCategory',
            new_name='ProductC',
        ),
    ]
